version: "3"
services:
  tw:
    image: tw
    container_name: twtest
    environment:
      - UID=99
      - GROUPS=99
    ports:
      - "9092:9091"

    volumes:
      - ./data/:/opt/
      - /drako/:/drako/

