version: "3"
services:
  tw:
    image: torrentwatcher
    container_name: tw
    environment:
      - UID=99
      - GROUPS=99
    ports:
      - "9091:9091"

    volumes:
      - ./data/:/opt/
      - /drako/:/drako/

