version: "3"
services:
  tw:
    image: tw
    container_name: twtest
    environment:
      - UID=99
      - GROUPS=99
      - RCLONE_CONFIG=/etc/rclone.conf
    ports:
      - "0.0.0.0:9092:9091"

    volumes:
      - ./data/:/opt/
      - /drako/:/drako/
      - ./tw.conf:/etc/tw.conf
      - ./rclone.conf:/etc/rclone.conf

